#!/bin/bash
LATEST_SHA="$(git rev-parse HEAD)"
MODIFIED_FILES="`git diff-tree --no-commit-id --name-only -r $LATEST_SHA -- bootcamps/**`"

# Needed?
# BASE_DIR="`pwd`"
# echo $BASE_DIR

for modfile in $MODIFIED_FILES ; do
  for directory in bootcamps/*/ ; do
    if [[ $modfile =~ $directory ]] ; then
      echo 'Detected changes in' $directory
      python script/validate_bootcamp_data.py --directory $directory
    fi
  done
done
