#!/bin/bash
for directory in bootcamps/*/ ; do
  python script/validate_bootcamp_data.py --directory $directory
  if [ '$?' = 1 ]; then
    SUCCESS=;
  fi
done

if [ $SUCCESS ]; then
  echo 'Looking good!'
  exit 0;
else
  echo "\033[0;31m[Errors found]\033[1;37m Lucy! You got some 'splaining to do. See logs above for more information.";
  exit 1;
fi
